name: 'Sous Formats'
description: 'A recipe that contains modules and configuration for Sous default date and text formats.'
type: 'Site'
install:
  - ckeditor5
  - editor
  - entity_embed
  - filter
  - media
config:
  import:
    filter:
      - filter.format.plain_text.yml
    media:
      - core.entity_view_mode.media.full
