name: 'Sous Emulsify'
description: 'A recipe that installs Emulsify dependencies and sets Emulsify as the default theme.'
type: 'Site'
install:
  - components
  - emulsify
  - emulsify_tools
config:
  actions:
    system.theme:
      simple_config_update:
        default: emulsify
