local_task_enabled_entity_types:
  - media
track_enabled_source_entity_types:
  - base_field_override
  - node
  - block_content
  - menu_link_content
  - file
  - media
  - taxonomy_term
track_enabled_target_entity_types:
  - base_field_override
  - node
  - block_content
  - menu_link_content
  - file
  - media
  - taxonomy_term
track_enabled_plugins:
  - entity_embed
  - entity_reference
  - dynamic_entity_reference
  - media_embed
  - block_field
  - link
  - html_link
track_enabled_base_fields: true
edit_warning_message_entity_types:
delete_warning_message_entity_types:
  - media
usage_controller_items_per_page: 25
