button_value: ''
button_weight: '-10'
unpublish: false
unpublish_new_only: false
hide_default_save: false
hide_default_publish: false
hide_default_preview: false
hide_default_delete: false
node_types:
  frontpage: '0'
  page: '0'
dropbutton: 0
