name: sous-project
recipe: drupal10
config:
  webroot: web
  php: "8.1"
  composer_version: '2'
  # M1/2 Mac settings
  xdebug: false
  index: false
  edge: false
  cache: false
services:
  appserver:
    build:
      - composer install
      - cp web/sites/default/default.settings.php web/sites/default/settings.php
    build_as_root:
      - apt-get update -qq -y && apt-get install -qq -y apt-transport-https build-essential unzip
      - apt-get install -qq chromium
      - apt-get update
      - apt-get install -y ca-certificates curl gnupg
      - mkdir -p /etc/apt/keyrings
      - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
      - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
      - apt-get update
      - apt-get install nodejs -y
      - chown -R www-data /usr/lib/node_modules
      - chown -R www-data /usr/bin
      - npm install --silent -g npm@latest
      - npm install --silent -g @emulsify/cli
    overrides:
      ports:
        - 6006:6006
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://sous-project.lndo.site"
  node:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver
  emulsify:
    service: appserver
  # Simplify and run scripts through lando
  confex:
    service: appserver
    description: "Export active configuration"
    cmd: npm run confex
  confim:
    service: appserver
    description: "Import configuration"
    cmd: npm run confim
  import-data:
    service: appserver
    description: "Import local database file"
    cmd: npm run import-data
  local-data-bak:
    service: appserver
    description: "Create a backup of the local database"
    cmd: npm run local-data-bak
  project-rebuild:
    service: appserver
    description: "Rebuild your project using a fresh database"
    cmd: npm run rebuild
  theme-build:
    service: appserver
    description: "Compile your theme files"
    cmd: npm run theme-build
  theme-watch:
    service: appserver
    description: "Watch for any theme changes and recompile"
    cmd: npm run theme-watch
  compound-install:
    service: appserver
    description: "Install Compound component library"
    cmd: cd $LANDO_MOUNT && cd web/themes/custom/sous-theme && emulsify system install compound
  install-recipe:
    service: appserver
    cmd: bash ./scripts/sous/install-recipe.sh
