name: sous-project
recipe: drupal10
config:
  webroot: web
  php: "8.1"
  composer_version: '2'
  # M1/2 Mac settings
  xdebug: false
  index: false
  edge: false
  cache: false
services:
  appserver:
    build:
      - composer install
      - cp web/sites/default/default.settings.php web/sites/default/settings.php
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - npm install --silent -g npm@latest
      - npm install --silent -g @emulsify/cli
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://sous-project.lndo.site"
  node:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver
  emulsify:
    service: appserver
  # Simplify and run scripts through lando
  confex:
    service: appserver
    description: "Export active configuration"
    cmd: npm run confex
  confim:
    service: appserver
    description: "Import configuration"
    cmd: npm run confim
  import-data:
    service: appserver
    description: "Import local database file"
    cmd: npm run import-data
  local-data-bak:
    service: appserver
    description: "Create a backup of the local database"
    cmd: npm run local-data-bak
  project-rebuild:
    service: appserver
    description: "Rebuild your project using a fresh database"
    cmd: npm run rebuild
  theme-build:
    service: appserver
    description: "Compile your theme files"
    cmd: npm run theme-build
  theme-watch:
    service: appserver
    description: "Watch for any theme changes and recompile"
    cmd: npm run theme-watch
  compound-install:
    service: appserver
    description: "Install Compound component library"
    cmd: cd $LANDO_MOUNT && cd web/themes/custom/sous-theme && emulsify system install compound
  install-recipe:
    service: appserver
    cmd: bash ./devops/scripts/install-recipe.sh
