version: 2.1
orbs:
  node: circleci/node@4.1.0
  php: circleci/php@1.1.0
jobs:
  build_node:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm ci
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm ci
      - run:
          command: npm run publish
workflows:
  version: 2
  build:
    jobs:
      - build_node
      - release:
          requires:
            - build_node
          filters:
            branches:
              only:
                - '+([0-9])?(.{+([0-9]),x}).x'
                - 'master'
