<?php

/**
 * @file
 * Taxonomy Manager.
 *
 * Administration interface for managing taxonomy vocabularies.
 */

/**
 * Implements hook_admin_menu_map().
 */
function taxonomy_manager_admin_menu_map() {
  if (!user_access('administer taxonomy')) {
    return;
  }
  $map['admin/structure/taxonomy_manager/voc/%taxonomy_vocabulary_machine_name'] = [
    'parent' => 'admin/structure/taxonomy_manager/voc',
    'arguments' => [
      ['%taxonomy_vocabulary_machine_name' => array_keys(taxonomy_vocabulary_get_names())],
    ],
  ];
  return $map;
}

/**
 * Implements hook_help().
 */
function taxonomy_manager_help($path, $arg) {
  switch ($path) {
    case 'admin/help#taxonomy_manager':
      $output = t("The Taxonomy Manager provides an additional interface for managing vocabularies of the taxonomy module. It's especially very useful for long sets of terms.
                   The vocabulary is represented in a dynamic tree view.
                   It supports operation like mass adding and deleting of terms, fast weight editing, moving of terms in hierarchies, merging of terms and fast term data editing.
                   For more information on how to use please read the readme file included in the taxonomy_manager directory.");
      return $output;
  }
}
