version: 2.1
orbs:
  node: circleci/node@5.0.3
  php: circleci/php@1.1.0
jobs:
  build_node:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm ci
  build_php:
    docker:
      - image: 'cimg/php:8.1'
    steps:
      - checkout
      - run: php --version
      - php/install-composer:
          install-version: 2.1.9
      - run:
          command: composer config -g github-oauth.github.com $COMPOSER_TOKEN
      - php/install-packages
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm ci
      - run:
          command: npm run publish
workflows:
  version: 2
  build:
    jobs:
      - build_node
      - build_php
      - release:
          requires:
            - build_node
            - build_php
          filters:
            branches:
              only:
                - '/^4.*/'
                - '/^3.*/'
                - '/^2.*/'
                - main
                - next
                - next-major
                - alpha
                - beta
