root: true
extends:
  - airbnb
  - prettier
  - prettier/react
  - plugin:prettier/recommended
plugins:
  - react
  - prettier
  - jest
env:
  es6: true
  browser: true
  jest/globals: true
globals:
  expect: true
  it: true
  describe: true
  Drupal: true
parser: babel-eslint
rules:
  strict: 0
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
  import/no-extraneous-dependencies: 0
  react/prefer-stateless-function: 0
  prettier/prettier: error
  jsx-a11y/label-has-for:
    - 2
    - required:
        some:
          - nesting
          - id
overrides:
  - files:
      - '*.stories.js'
    rules:
      react/no-danger: 0
