name: 'Sous Paragraph Types'
description: 'A recipe that contains modules and configuration for the default Sous paragraphs types.'
type: 'Site'
recipes:
  - sous_content_types
  - sous_media
install:
  # Core modules
  - file
  - image
  - media
  - media_library
  - options
  - paragraphs
  - paragraphs_collapsible
  - paragraphs_ee
  - paragraphs_features
  - taxonomy
  - views
  # Contrib modules
  - focal_point
  - media_library_edit
config:
  import:
    # Core.
    image: '*'
    media: '*'
    media_library: '*'
    # Contrib.
    focal_point: '*'