_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  components: 0
  config: 0
  config_filter: 0
  config_split: 0
  contextual: 0
  crop: 0
  ctools: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  emulsify_twig: 0
  entity_browser: 0
  entity_browser_enhanced: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  gin_toolbar: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jquery_ui: 0
  libraries: 0
  link: 0
  linkit: 0
  login_history: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_collapsible: 0
  paragraphs_features: 0
  path: 0
  path_alias: 0
  redirect: 0
  responsive_image: 0
  role_delegation: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  paragraphs_ee: 15
  minimal: 1000
theme:
  stark: 0
  claro: 0
  gin: 0
profile: minimal
