name: 'Sous Base'
description: 'A recipe to install a base Sous Drupal project with Emulsify dependencies.'
type: 'Site'
install:
  - components
  - emulsify
  - emulsify_tools
config:
  actions:
    system.theme:
      simple_config_update:
        default: emulsify
