name: 'Sous Base'
description: 'A recipe to install a base Sous Drupal project.'
type: 'Site'

install:
  - help
  - gin
  - gin_toolbar
config:
  import:
    gin:
      - gin.settings
  actions:
    system.theme:
      simple_config_update:
        default: sous-project
        admin: gin