name: 'Sous Base'
description: 'A recipe to install a base Sous Drupal project.'
type: 'Site'

install:
  - help
  - gin
  - gin_toolbar
config:
  import:
    gin: '*'
  actions:
    system.theme:
      simple_config_update:
        default: sous-theme
        admin: gin