name: 'Sous Base'
description: 'A recipe to install a base Sous Drupal project with Emulsify dependencies.'
type: 'Site'
install:
  - components
  - emulsify_twig
  - sousdrupalrecipe
config:
  actions:
    system.theme:
      simple_config_update:
        default: sousdrupalrecipe
