#!/bin/bash

## Description: Install a Drupal recipe
## Usage: install-recipe [full package name]
## Example: ddev install-recipe fourkitchens/sous-admin

recipe_full_package_name="$1"
IFS='/' read -ra recipe_split <<< "$recipe_full_package_name"
recipe_directory_name="${recipe_split[1]}"

if [ $# -eq 0 ]; then
 echo "Usage: specify the directory name inside of /app/recipes/ that you want to install:"
 cd /app/recipes/
 ls -d -- */
 exit 1
fi

cd web
php core/scripts/drupal recipe recipes/"$recipe_directory_name"
../vendor/bin/drush cr
