google_tag.settings:
  type: config_object
  label: 'Module settings and default container settings'
  mapping:
    uri:
      type: string
      label: 'Snippet base URI'
    compact_snippet:
      type: boolean
      label: 'Compact the JavaScript snippet'
    include_file:
      type: boolean
      label: 'Include the snippet as a file'
    rebuild_snippets:
      type: boolean
      label: 'Recreate snippets on cache rebuild'
    flush_snippets:
      type: boolean
      label: 'Recreate snippet directory on cache rebuild'
    debug_output:
      type: boolean
      label: 'Show debug output'
    _default_container:
      type: _google_tag_container

google_tag.container.*:
  type: config_entity
  label: 'Container settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    #_container:
      #type: _google_tag_container
    container_id:
      type: string
      label: 'Container ID'
      #translatable: true
    data_layer:
      type: string
      label: 'Data layer'
      #translatable: true
    include_classes:
      type: boolean
      label: 'Add classes to the data layer'
    whitelist_classes:
      type: string
      label: 'White-listed classes'
      #translatable: true
    blacklist_classes:
      type: string
      label: 'Black-listed classes'
      #translatable: true
    include_environment:
      type: boolean
      label: 'Include an environment'
    environment_id:
      type: string
      label: 'Environment ID'
      #translatable: true
    environment_token:
      type: string
      label: 'Environment token'
      #translatable: true
    path_toggle:
      type: string
      label: 'Add snippet on specific paths'
      #translatable: true
    path_list:
      type: string
      label: 'Listed paths'
      #translatable: true
    role_toggle:
      type: string
      label: 'Add snippet for specific roles'
      #translatable: true
    role_list:
      type: sequence
      label: 'Selected roles'
      sequence:
        type: string
        label: 'Role'
      #translatable: true
    status_toggle:
      type: string
      label: 'Add snippet for specific statuses'
      #translatable: true
    status_list:
      type: string
      label: 'Listed statuses'
      #translatable: true
    conditions:
      type: sequence
      label: 'Insertion conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Insertion condition'
