name: 'Sous Content Types'
description: 'A recipe that contains modules and configuration for Sous default content types.'
type: 'Sous'

install:
  # Install core dependencies.
  - metatag
  - node
  - publication_date
  - text
  - user

