name: 'Sous Content Types'
description: 'A recipe that contains modules and configuration for Sous default content types.'
type: 'Sous'

install:
  # Install core dependencies.
  - metatag
  - node
  - publication_date
  - text
  - user

config:
  import:
    metatag: '*'
  actions:
    # Update metatag default node settings
    metatag.metatag_defaults.node:
      simple_config_update:
        tags:
          canonical_url: '[node:url]'
          description: '[node:field_teaser_text]'
          title: '[node:field_seo_title]'
